<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="ScoreWebServiceService" targetNamespace="http://soap.source.passcop.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://soap.source.passcop.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://soap.source.passcop.com/" schemaLocation="ScoreWebServiceService_schema1.xsd"></import>
</schema>
  </wsdl:types>
  <wsdl:message name="ConsultarServicioPersona">
    <wsdl:part name="parameters" element="tns:ConsultarServicioPersona">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="ConsultarServicioPersonaResponse">
    <wsdl:part name="parameters" element="tns:ConsultarServicioPersonaResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="EnviarDatosOperacion">
    <wsdl:part name="parameters" element="tns:EnviarDatosOperacion">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="EnviarDatosOperacionResponse">
    <wsdl:part name="parameters" element="tns:EnviarDatosOperacionResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="ScoreWebService">
    <wsdl:operation name="ConsultarServicioPersona">
      <wsdl:input name="ConsultarServicioPersona" message="tns:ConsultarServicioPersona">
    </wsdl:input>
      <wsdl:output name="ConsultarServicioPersonaResponse" message="tns:ConsultarServicioPersonaResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="EnviarDatosOperacion">
      <wsdl:input name="EnviarDatosOperacion" message="tns:EnviarDatosOperacion">
    </wsdl:input>
      <wsdl:output name="EnviarDatosOperacionResponse" message="tns:EnviarDatosOperacionResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ScoreWebServiceServiceSoapBinding" type="tns:ScoreWebService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ConsultarServicioPersona">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="ConsultarServicioPersona">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="ConsultarServicioPersonaResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="EnviarDatosOperacion">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="EnviarDatosOperacion">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="EnviarDatosOperacionResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ScoreWebServiceService">
    <wsdl:port name="ScoreWebServicePort" binding="tns:ScoreWebServiceServiceSoapBinding">
      <soap:address location="http://localhost:9090/ScoreWebServicePort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
