
package com.passcop.source.soap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Tue Aug 10 15:27:46 ECT 2021
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "ConsultarServicioPersona", namespace = "http://soap.source.passcop.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConsultarServicioPersona", namespace = "http://soap.source.passcop.com/", propOrder = {"identificacion", "UsuarioID"})

public class ConsultarServicioPersona {

    @XmlElement(name = "identificacion")
    private java.lang.String identificacion;
    @XmlElement(name = "UsuarioID")
    private java.lang.Short UsuarioID;

    public java.lang.String getIdentificacion() {
        return this.identificacion;
    }

    public void setIdentificacion(java.lang.String newIdentificacion)  {
        this.identificacion = newIdentificacion;
    }

    public java.lang.Short getUsuarioID() {
        return this.UsuarioID;
    }

    public void setUsuarioID(java.lang.Short newUsuarioID)  {
        this.UsuarioID = newUsuarioID;
    }

}

