package com.passcop.source.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2022-01-25T21:31:10.364-05:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://soap.source.passcop.com/", name = "ScoreWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface ScoreWebService {

    @WebMethod(operationName = "ConsultarServicioPersona")
    @RequestWrapper(localName = "ConsultarServicioPersona", targetNamespace = "http://soap.source.passcop.com/", className = "com.passcop.source.soap.ConsultarServicioPersona")
    @ResponseWrapper(localName = "ConsultarServicioPersonaResponse", targetNamespace = "http://soap.source.passcop.com/", className = "com.passcop.source.soap.ConsultarServicioPersonaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.passcop.source.soap.Persona consultarServicioPersona(
        @WebParam(name = "identificacion", targetNamespace = "")
        java.lang.String identificacion,
        @WebParam(name = "UsuarioID", targetNamespace = "")
        java.lang.Short usuarioID
    );

    @WebMethod(operationName = "EnviarDatosOperacion")
    @RequestWrapper(localName = "EnviarDatosOperacion", targetNamespace = "http://soap.source.passcop.com/", className = "com.passcop.source.soap.EnviarDatosOperacion")
    @ResponseWrapper(localName = "EnviarDatosOperacionResponse", targetNamespace = "http://soap.source.passcop.com/", className = "com.passcop.source.soap.EnviarDatosOperacionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.passcop.source.soap.RespuestaSolicitud enviarDatosOperacion(
        @WebParam(name = "operacion", targetNamespace = "")
        com.passcop.source.soap.Respuesta operacion
    );
}
