
package com.passcop.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2021-08-03T22:57:44.992-05:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "Exception", targetNamespace = "http://soap.source.passcop.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.passcop.client.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.passcop.client.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.passcop.client.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.passcop.client.Exception getFaultInfo() {
        return this.exception;
    }
}
