package com.passcop.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2021-08-31T14:24:41.153-05:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://soap.source.passcop.com/", name = "ScoreWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface ScoreWebService {

    @WebMethod(operationName = "ConsultarServicioPersona")
    @RequestWrapper(localName = "ConsultarServicioPersona", targetNamespace = "http://soap.source.passcop.com/", className = "com.passcop.client.ConsultarServicioPersona")
    @ResponseWrapper(localName = "ConsultarServicioPersonaResponse", targetNamespace = "http://soap.source.passcop.com/", className = "com.passcop.client.ConsultarServicioPersonaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.passcop.client.Persona consultarServicioPersona(
        @WebParam(name = "identificacion", targetNamespace = "")
        java.lang.String identificacion,
        @WebParam(name = "UsuarioID", targetNamespace = "")
        java.lang.Short usuarioID
    );

    @WebMethod(operationName = "EnviarDatosOperacion")
    @RequestWrapper(localName = "EnviarDatosOperacion", targetNamespace = "http://soap.source.passcop.com/", className = "com.passcop.client.EnviarDatosOperacion")
    @ResponseWrapper(localName = "EnviarDatosOperacionResponse", targetNamespace = "http://soap.source.passcop.com/", className = "com.passcop.client.EnviarDatosOperacionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.passcop.client.RespuestaSolicitud enviarDatosOperacion(
        @WebParam(name = "operacion", targetNamespace = "")
        com.passcop.client.Respuesta operacion
    );
}
